# lextab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('ASSIGN', 'BOOL', 'BOOL_AND', 'BOOL_NOT', 'BOOL_OR', 'COMMA', 'CONST_FLOAT', 'CONST_INT', 'CONST_STRING', 'DEF', 'DIVIDE', 'DOT', 'ELIF', 'ELSE', 'EQUALS', 'FLOAT', 'FOR', 'GT', 'GTE', 'ID', 'IF', 'INPUT', 'INT', 'LCURLY_BRACKET', 'LPARENTHESIS', 'LSQUARE_BRACKET', 'LT', 'LTE', 'MAIN', 'MINUS', 'NOT_EQUALS', 'PLUS', 'PRINT', 'RCURLY_BRACKET', 'RETURN', 'RPARENTHESIS', 'RSQUARE_BRACKET', 'SEMICOLON', 'STRING', 'TIMES', 'VAR', 'VOID', 'WHILE'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_ID>[A-Za-z_][A-Za-z0-9_]*)|(?P<t_space>[ \\f\\r\\t\\v]+)|(?P<t_newline>\\n+)|(?P<t_COMMENT>\\#.*)|(?P<t_CONST_FLOAT>[0-9]+\\.[0-9]+)|(?P<t_CONST_INT>[0-9]+)|(?P<t_CONST_STRING>\\"([^\\\\\\n]|(\\\\.))*?\\")|(?P<t_BOOL_OR>\\|\\|)|(?P<t_EQUALS>==)|(?P<t_NOT_EQUALS>!=)|(?P<t_GTE>>=)|(?P<t_LTE><=)|(?P<t_BOOL_AND>&&)|(?P<t_PLUS>\\+)|(?P<t_MINUS>\\-)|(?P<t_TIMES>\\*)|(?P<t_LPARENTHESIS>\\()|(?P<t_RPARENTHESIS>\\))|(?P<t_LCURLY_BRACKET>\\{)|(?P<t_RCURLY_BRACKET>\\})|(?P<t_LSQUARE_BRACKET>\\[)|(?P<t_RSQUARE_BRACKET>\\])|(?P<t_DOT>\\.)|(?P<t_GT>>)|(?P<t_LT><)|(?P<t_BOOL_NOT>!)|(?P<t_DIVIDE>/)|(?P<t_ASSIGN>=)|(?P<t_COMMA>,)|(?P<t_SEMICOLON>;)', [None, ('t_ID', 'ID'), ('t_space', 'space'), ('t_newline', 'newline'), ('t_COMMENT', 'COMMENT'), ('t_CONST_FLOAT', 'CONST_FLOAT'), ('t_CONST_INT', 'CONST_INT'), ('t_CONST_STRING', 'CONST_STRING'), None, None, (None, 'BOOL_OR'), (None, 'EQUALS'), (None, 'NOT_EQUALS'), (None, 'GTE'), (None, 'LTE'), (None, 'BOOL_AND'), (None, 'PLUS'), (None, 'MINUS'), (None, 'TIMES'), (None, 'LPARENTHESIS'), (None, 'RPARENTHESIS'), (None, 'LCURLY_BRACKET'), (None, 'RCURLY_BRACKET'), (None, 'LSQUARE_BRACKET'), (None, 'RSQUARE_BRACKET'), (None, 'DOT'), (None, 'GT'), (None, 'LT'), (None, 'BOOL_NOT'), (None, 'DIVIDE'), (None, 'ASSIGN'), (None, 'COMMA'), (None, 'SEMICOLON')])]}
_lexstateignore = {'INITIAL': '\t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
